version: "3"

networks:
  shared:
    external: false

services:
  &api-web-service api-web-service:
    container_name: Nexus_container
    domainname: Nexus
    image: node:16
    user: "1000"
    ports:
      - 6969:6969
    volumes:
      - ../server:/home/node/app
    working_dir: /home/node/app
    restart: unless-stopped
    command: npm run start:dev
    networks:
      - shared
